/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-LPI_transmit
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_LPI_TRANSMIT_API_H
#define INCLUDED_LPI_TRANSMIT_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_LPI_transmit_EXPORTS
#define LPI_TRANSMIT_API __GR_ATTR_EXPORT
#else
#define LPI_TRANSMIT_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_LPI_TRANSMIT_API_H */
